name: Release with versio
description: Release a project using versio
outputs:
  version_bump:
    description: Did the version change?
    value: ${{ steps.version_bump.outputs.version_bump }}
  current_version:
    description: The current version
    value: ${{ steps.current_version.outputs.current_version }}
  previous_version:
    description: The previous version
    value: ${{ steps.previous_version.outputs.previous_version }}

runs:
  using: composite
  steps:
  - uses: actions/checkout@v3
    name: Checkout the repository
    with:
      fetch-depth: 0
  - uses: chaaz/versio-actions/install@v1.2
    name: Install versio
  - id: previous_version
    name: Get the previous version
    run: echo ::set-output "name=previous_version::$( versio get --id 1 -v )"
    shell: bash
  - name: Generate release
    shell: bash
    run: |
      if versio release --dry-run | grep -qF " -> "  ; then
        versio release
      fi
    env:
      GITHUB_TOKEN: ${{ github.token }}
      GITHUB_USER: ${{ github.actor }}
  - run: echo ::set-output "name=current_version::$( versio get --id 1 -v )"
    id: current_version
    name: Get the current version
    shell: bash
  - run: |
      if [ "$CURR" != "$PREV" ] ; then
        echo ::set-output "name=version_bump::true"
      fi
    id: version_bump
    shell: bash
    name: Did the version bump
    env:
      CURR: ${{ steps.current_version.outputs.current_version }}
      PREV: ${{ steps.previous_version.outputs.previous_version }}
