name: Generate a changelog
description: Generate a changelog using git-cliff with a default config
inputs:
  config:
    description: config file location
    required: false
    default: cliff.toml
  args:
    description: git-cliff arguments
    required: false
    default: -v
  output:
    description: Output file
    required: false
    default: CHANGELOG.md
outputs:
  version_bump:
    description: Did the version change?
    value: ${{ steps.version_bump.outputs.version_bump }}
  current_version:
    description: The current version
    value: ${{ steps.current_version.outputs.current_version }}
  previous_version:
    description: The previous version
    value: ${{ steps.previous_version.outputs.previous_version }}

runs:
  using: composite
  steps:
  - uses: actions/checkout@v2.3.5
    with:
      fetch-depth: 0
  - uses: chaaz/versio-actions/install@v1.2
    name: Install versio
  - id: previous_version
    run: echo ::set-output "name=previous_version::$( versio get --id 1 -v )"
    shell: bash
  - name: Generate release
    shell: bash
    run: |
      if [ "$(versio release --dry-run)" == *" -> "* ] ; then
        versio release
      fi
    env:
      GITHUB_TOKEN: ${{ github.token }}
      GITHUB_USER: ${{ github.actor }}
  - run: echo ::set-output "name=current_version::$( versio get --id 1 -v )"
    id: current_version
    shell: bash
  - run: |
      if [ "$CURR" == "$PREV" ] ; then
        echo ::set-output "name=version_bump::true"
      fi
    id: version_bump
    shell: bash
    env:
      CURR: ${{ steps.current_version.outputs.current_version }}
      PREV: ${{ steps.previous_version.outputs.previous_version }}