name: Release with versio
description: Release a project using versio
outputs:
  version_bump:
    description: Did the version change?
    value: ${{ steps.version_bump.outputs.version_bump }}
  current_version:
    description: The current version
    value: ${{ steps.current_version.outputs.current_version }}
  previous_version:
    description: The previous version
    value: ${{ steps.previous_version.outputs.previous_version }}

runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
    name: Checkout the repository
    with:
      fetch-depth: 0
  - name: Install versio
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install -y libgpgme11-dev
      cargo install versio
  - id: previous_version
    name: Get the previous version
    run: echo "previous_version=$( versio get --id 1 -v )" >> "$GITHUB_OUTPUT"
    shell: bash
  - name: Generate release
    shell: bash
    run: |
      if versio release --dry-run | grep -qF " -> "  ; then
        versio release
      fi
    env:
      GITHUB_TOKEN: ${{ github.token }}
      GITHUB_USER: ${{ github.actor }}
  - run: echo "current_version=$( versio get --id 1 -v )" >> "$GITHUB_OUTPUT"
    id: current_version
    name: Get the current version
    shell: bash
  - run: |
      if [ "$CURR" != "$PREV" ] ; then
        echo "version_bump=true" >> "$GITHUB_OUTPUT"
      fi
    id: version_bump
    shell: bash
    name: Did the version bump
    env:
      CURR: ${{ steps.current_version.outputs.current_version }}
      PREV: ${{ steps.previous_version.outputs.previous_version }}
